DMD09LEAFL-4: Add basic css for leaflet maps
digipolisgent/drupal_theme_gent-base pull request #1006
Opened 2024-07-02 07:28 UTC by orabina

## Description
Add basic css to the leaflet maps 
[ticket](https://district09.atlassian.net/browse/DMD09LEAFL-4) 

## Motivation and Context
As preparation to remove DG maps and replace them with leaflet maps 

## Screenshots (if appropriate):

![image](https://github.com/StadGent/drupal_theme_gent-base/assets/48244596/3ced08f5-4fd9-4bf2-9829-01799a7ceb0b)

2024-07-02 10:59 UTC, lennartvava requested changes

2024-07-02 10:59 UTC, lennartvava commented on source/sass/31-molecules/map/_map.scss
> +// D09 leaflet maps
Geen verwijzing naar projecten of bedrijven zetten. Gent Base is een projectonafhankelijk Drupal thema dat in eender welk drupal project gebruikt kan worden en aangeboden wordt vanuit Stad Gent.

Als al deze styling op leaflets toegepast is, mag je dit als een molecule in _leaflet.scss zetten onder de "map" folder.

Ter info: Idealiter zit de maps styling in de (fractal) stijlgids, maar dat is momenteel ook nog niet het geval, dus het mag in gent_base blijven zitten voor nu.

2024-07-02 10:59 UTC, lennartvava commented on source/sass/31-molecules/map/_map.scss
> +        margin-bottom: .5rem;
Margins en paddings van elementen mogen in px staan: 10px

2024-07-02 13:01 UTC, lennartvava commented
Het gebruik van color() in sass zou ik proberen minimaliseren en de voorkeur geven aan theme(). Ik zal dit eerstdaags toelichten in kader van de fractal stijlgids.

2024-07-02 13:02 UTC, lennartvava approved these changes

2024-07-02 13:26 UTC, zero2one requested changes

2024-07-02 13:26 UTC, zero2one commented on source/sass/31-molecules/map/_leaflet.scss
> +      background: color('white') url('#{$styleguide-dir}/img/svg/fullscreen-enter.svg') no-repeat 10px 10px;
Use the variables you have defined.
```scss
background: $map-button-background url(...
```

2024-07-02 13:26 UTC, zero2one commented on source/sass/31-molecules/map/_leaflet.scss
> +        background: color('white') url('#{$styleguide-dir}/img/svg/fullscreen-exit.svg') no-repeat 10px 10px;
Use the variables you have defined.
```scss
background: $map-button-background url(...
```

2024-07-02 13:26 UTC, zero2one commented on source/sass/31-molecules/map/_leaflet.scss
> +        background: color('white') url('#{$styleguide-dir}/img/svg/target.svg') no-repeat 10px 10px;
Use the variables you have defined.
```scss
background: $map-button-background url(...
```

2024-07-02 13:26 UTC, zero2one commented on source/sass/31-molecules/map/_leaflet.scss
> +      background: color('white') url('#{$styleguide-dir}/img/svg/layers.svg') no-repeat 10px 10px;
Use the variables you have defined.
```scss
background: $map-button-background url(...
```

2024-07-05 13:49 UTC, zero2one approved these changes

2024-07-08 06:48 UTC, merged

2024-07-17 09:49 UTC, lennartvava commented on source/sass/31-molecules/map/_leaflet.scss
> +      box-shadow: 0 8px 12px 0 rgba(0, 125, 179, .06);
Use the box shadow mixin.