DTGB-426: Added table of contents to the preview template.
digipolisgent/drupal_theme_gent-base pull request #136
Opened 2018-05-22 12:11 UTC by meirege

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.

2018-05-22 13:37 UTC, delrueba requested changes

2018-05-22 13:37 UTC, delrueba commented on styleguide/components/51-templates/styleguide/styleguide.twig
> +    <h2>Table of contents</h2>
Should be in a nav region.
Identify which nav region it is by using aria-labelledby (refer to the heading element for instance)

see: https://inclusive-components.design/menus-menu-buttons/#tablesofcontent

2018-05-22 13:44 UTC, meirege commented on styleguide/components/51-templates/styleguide/styleguide.twig
> +    <h2>Table of contents</h2>
Fixed it.

2018-05-22 15:09 UTC, delrueba requested changes

2018-05-22 15:09 UTC, delrueba commented on styleguide/components/51-templates/styleguide/styleguide.twig
> +    <nav aria-labelledby="table-of-contents-section">
Closing tag missing

2018-05-23 09:35 UTC, meirege commented on styleguide/components/51-templates/styleguide/styleguide.twig
> +    <nav aria-labelledby="table-of-contents-section">
Fixed.

2018-05-23 10:06 UTC, delrueba approved these changes

2018-05-23 10:06 UTC, merged