[DTGB-450] Nieuwsteaser
digipolisgent/drupal_theme_gent-base pull request #190
Opened 2018-06-15 13:29 UTC by Jeroen005

# Ticket
Link to ticket: https://digipolisgent.atlassian.net/browse/DTGB-450

2018-06-15 14:53 UTC, meirege approved these changes

2018-06-18 09:15 UTC, delrueba requested changes

2018-06-18 09:15 UTC, delrueba commented on templates/custom/nodes/node--event--teaser.html.twig
> +        <time{{ author_attributes.addClass('published') }}>
Event's display event dates, not published date.

2018-06-18 09:15 UTC, delrueba commented on templates/custom/nodes/node--news--teaser.html.twig
> +        <time{{ author_attributes.addClass('published') }}>
Missing datetime attribute.

2018-06-18 11:49 UTC, meirege approved these changes

2018-06-18 13:52 UTC, delrueba approved these changes

2018-06-18 13:54 UTC, merged