DTGB-276: Fixed breadcrumbs padding issue in styleguide and gent_base.
digipolisgent/drupal_theme_gent-base pull request #22
Opened 2018-02-12 15:06 UTC by meirege

## Description
Fixed whitespace issue + JS issue in gent_base. 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the style guide CHANGELOG accordingly.
- [x] I have updated the gent_base CHANGELOG accordingly.

2018-02-12 15:37 UTC, delrueba requested changes

2018-02-12 15:37 UTC, delrueba commented on styleguide/components/31-molecules/building-blocks/breadcrumbs/breadcrumbs.twig
> +      {% for item in items %}
Suggest adding [{% spaceless %}](https://twig.symfony.com/doc/2.x/tags/spaceless.html)
See: https://codepen.io/chriscoyier/pen/hmlqF

2018-02-12 15:37 UTC, delrueba commented on templates/navigation/breadcrumb.html.twig
> +          <li>
Suggest adding {% spaceless %}

2018-02-12 15:40 UTC, delrueba requested changes

2018-02-12 15:40 UTC, delrueba commented on styleguide/components/31-molecules/building-blocks/breadcrumbs/_breadcrumbs.scss
> +          background-color: $bg-hover-breadcrumb;
There's a mixin to include :focus

2018-02-12 15:40 UTC, delrueba commented on templates/layout/page.html.twig
> +          <nav class="hamburger-menu visible-mobile header-compone .5rem -.35renfinmnt">
Typo?

2018-02-13 09:11 UTC, meirege commented on templates/navigation/breadcrumb.html.twig
> +          <li>
Agreed. Added.

2018-02-13 09:11 UTC, meirege commented on templates/layout/page.html.twig
> +          <nav class="hamburger-menu visible-mobile header-compone .5rem -.35renfinmnt">
Fixed

2018-02-13 09:11 UTC, meirege commented on styleguide/components/31-molecules/building-blocks/breadcrumbs/breadcrumbs.twig
> +      {% for item in items %}
Agreed. Added.

2018-02-13 09:11 UTC, meirege commented on styleguide/components/31-molecules/building-blocks/breadcrumbs/_breadcrumbs.scss
> +          background-color: $bg-hover-breadcrumb;
Used the element-status() mixin as suggested.

2018-02-13 09:46 UTC, delrueba approved these changes

2018-02-20 13:44 UTC, merged