DTGB-397: Changed the way radio buttons and checkboxes are styled and…
digipolisgent/drupal_theme_gent-base pull request #23
Opened 2018-02-13 08:46 UTC by meirege

## Description
Changed the way radio buttons and checkboxes are styled and applied fixes to the gent_base templates to reflect this.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the style guide CHANGELOG accordingly.
- [x] I have updated the gent_base CHANGELOG accordingly.

2018-02-16 12:33 UTC, Jeroen005 requested changes

2018-02-16 12:33 UTC, Jeroen005 commented on templates/form/form-element-label.html.twig
> +        <span class="label-optional">({% trans %}Optional{% endtrans %})</span>
{{ 'Optional'|t }}

2018-02-19 08:47 UTC, meirege commented on templates/form/form-element-label.html.twig
> +        <span class="label-optional">({% trans %}Optional{% endtrans %})</span>
Fixed.

2018-02-19 10:19 UTC, Jeroen005 approved these changes

2018-02-19 15:36 UTC, merged