[DTGB-469] Main menu
digipolisgent/drupal_theme_gent-base pull request #240
Opened 2018-07-02 10:07 UTC by Jeroen005

# Ticket
Link to ticket: https://digipolisgent.atlassian.net/browse/DTGB-469

2018-07-02 10:10 UTC, Jeroen005 commented
Die duplicate code in codeclimate is wrs een non issue @delrueba ?

2018-07-02 11:03 UTC, delrueba requested changes

2018-07-02 11:03 UTC, delrueba commented on styleguide/components/31-molecules/menu/menu.functions.js
> +      // jquery .css() doesn't now 'important'
Typo,
not sure if we still need this warning.

2018-07-02 11:17 UTC, delrueba commented
There are unresolved sass errors.

2018-07-03 16:01 UTC, delrueba approved these changes

2018-07-03 16:02 UTC, merged