DTGB-402: Added a required fields indicator to forms.
digipolisgent/drupal_theme_gent-base pull request #26
Opened 2018-02-13 12:16 UTC by meirege

## Description
As described on https://digipolisgent.atlassian.net/wiki/spaces/HSSG/pages/11960359/Formulier+elementen
Form fields require an indicator to tell the user all fields are required unless stated otherwise.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.

2018-02-16 12:31 UTC, Jeroen005 requested changes

2018-02-16 12:31 UTC, Jeroen005 commented on styleguide/components/51-templates/forms/forms--with-errors.twig
> +      'text' : 'Vul alle velden in tenzij anders vermeld',
English :)

2018-02-16 12:31 UTC, Jeroen005 commented on styleguide/components/51-templates/forms/forms.twig
> +      'text' : 'Vul alle velden in tenzij anders vermeld',
English :)

2018-02-16 12:31 UTC, Jeroen005 commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +            'text' : 'Vul alle velden in tenzij anders vermeld',
English :)

2018-02-16 12:31 UTC, Jeroen005 commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +                  "label_radio1": "Ik reserveer deze zaal als particulier of feitelijke vereniging",
English :)

2018-02-16 12:31 UTC, Jeroen005 commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +                  "radio1_label": "Ik reserveer deze zaal als particulier of feitelijke vereniging",
English :)

2018-02-16 12:31 UTC, Jeroen005 commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +                  "label_radio2": "Ik reserveer deze zaal als particulier of feitelijke vereniging",
English :)

2018-02-16 12:31 UTC, Jeroen005 commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +                  "radio2_label": "Ik reserveer deze zaal als vennootschap of een vereniging met rechtspersoonlijkheid",
English :)

2018-02-19 08:43 UTC, meirege commented on styleguide/components/51-templates/forms/forms--with-errors.twig
> +      'text' : 'Vul alle velden in tenzij anders vermeld',
Fixed.

2018-02-19 08:43 UTC, meirege commented on styleguide/components/51-templates/forms/forms.twig
> +      'text' : 'Vul alle velden in tenzij anders vermeld',
Fixed.

2018-02-19 08:43 UTC, meirege commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +            'text' : 'Vul alle velden in tenzij anders vermeld',
Fixed.

2018-02-19 08:43 UTC, meirege commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +                  "label_radio1": "Ik reserveer deze zaal als particulier of feitelijke vereniging",
Fixed.

2018-02-19 08:43 UTC, meirege commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +                  "radio1_label": "Ik reserveer deze zaal als particulier of feitelijke vereniging",
Fixed.

2018-02-19 08:43 UTC, meirege commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +                  "label_radio2": "Ik reserveer deze zaal als particulier of feitelijke vereniging",
Fixed.

2018-02-19 08:43 UTC, meirege commented on styleguide/components/61-layouts/forms/form-with-steps/form-with-steps.twig
> +                  "radio2_label": "Ik reserveer deze zaal als vennootschap of een vereniging met rechtspersoonlijkheid",
Fixed.

2018-02-19 10:18 UTC, Jeroen005 approved these changes

2018-02-19 15:21 UTC, merged