DTGB-547: Added icons overview.
digipolisgent/drupal_theme_gent-base pull request #398
Opened 2018-09-12 12:12 UTC by zero2one

Added the icons overview to the icon atom page.

## Description

Added overview of all icons as supported by the Ghent icon font.

## Motivation and Context

Make it easier for theme maintainers and users to know what the available icons are.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have updated the documentation accordingly.
- [x] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.

2018-09-12 12:36 UTC, delrueba requested changes
We zetten alle config files systematisch om naar config.js
Dan kan je variants aanmaken en de collate functie gebruiken om ze allemaal in één preview te stoppen in een description list.

Zie buttons en links.

2018-09-12 12:37 UTC, delrueba commented
Tof! Zal de gebruiksvriendelijkheid ten goede komen.

Zou je na de refactor gulp axe willen laten lopen?
Ik heb alle fouten vorige week opgelost, dus je zou geen mogen hebben.

@meirege ging eens de pr description aanpassen daarvoor ;).

2018-09-13 11:14 UTC, meirege approved these changes

2018-09-14 11:11 UTC, meirege commented
@delrueba @zero2one What's the status of this PR?

2018-09-17 08:00 UTC, zero2one commented
* I replaced the .json config file by a .js config file.
* I replaced the list of icons by a list of variants.

2018-09-17 08:06 UTC, delrueba commented on styleguide/components/21-atoms/icon/icon.config.js
> +  preview: '@preview',
Is there a reason you don't use the dl-preview and dl collator function?

2018-09-17 08:29 UTC, delrueba approved these changes

2018-09-17 08:35 UTC, merged