DTGB-107: Disabled IE compatibility.
digipolisgent/drupal_theme_gent-base pull request #411
Opened 2018-09-14 11:24 UTC by meirege

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.
- [ ] I have ran gulp axe on the compiled files and found no errors.

2018-09-17 07:43 UTC, delrueba requested changes

2018-09-17 07:43 UTC, delrueba commented on gent_base.theme
> + */
Add additional comments.

2018-10-09 14:52 UTC, delrueba commented
@meirege any news on this pull request?

2018-10-15 07:13 UTC, meirege commented on gent_base.theme
> + */
Done.

2018-10-15 11:13 UTC, delrueba approved these changes

2018-10-15 11:13 UTC, merged