DTGB-576: Change footer region implementation
digipolisgent/drupal_theme_gent-base pull request #430
Opened 2018-10-09 14:42 UTC by hstandaert

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.
- [ ] I have ran gulp axe on the compiled files and found no errors.

2018-10-09 14:46 UTC, meirege approved these changes

2018-10-09 14:47 UTC, delrueba requested changes

2018-10-09 14:47 UTC, delrueba commented on templates/core/layout/page.html.twig
> +              <h2 class="visually-hidden">{{ 'Footer'|t }}</h2>
Not sure if this one is in the right place.
Footer and the optional subsite footer both have their own visually hidden h2.

2018-10-09 14:58 UTC, meirege approved these changes

2018-10-10 07:31 UTC, delrueba approved these changes

2018-10-10 07:32 UTC, merged