DTGB-580: Added check to fix error.
digipolisgent/drupal_theme_gent-base pull request #445
Opened 2018-10-15 14:47 UTC by meirege

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.
- [ ] I have ran gulp axe on the compiled files and found no errors.

2018-10-15 15:11 UTC, MPParsley requested changes
This will result in a notice;

Notice: Undefined index: #object in gent_base_preprocess_node__outdoor_location__teaser()

2018-10-16 06:56 UTC, meirege commented
@MPParsley Hoe check ik dan best hierop zodat ik geen notice krijg?

2018-10-16 07:33 UTC, MPParsley commented
Je kan hiervoor isset() gebruiken.

2018-10-16 12:53 UTC, MPParsley commented on gent_base.theme
> +  }
if (!isset($variables['elements']['field_related_terrains']['#object'])) {
    return;
  }
  $related_terrains = $variables['elements']['field_related_terrains']['#object'];

2018-10-16 12:56 UTC, meirege commented on gent_base.theme
> +  }
Fixed.

2018-10-16 12:56 UTC, MPParsley approved these changes

2018-10-16 12:57 UTC, MPParsley commented on gent_base.theme
> +  if (!$related_terrains) {
deze lijkt me niet meer nodig?

2018-10-16 13:06 UTC, merged