d8 gent-base integration of infobox
digipolisgent/drupal_theme_gent-base pull request #508
Opened 2018-11-23 09:23 UTC by hstandaert

## Description

Display infobox on: 
- Events
- News
- Infopoages

## Motivation and Context

## How Has This Been Tested?

Locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.
- [x] I have ran gulp axe on the compiled files and found no errors.

2018-11-23 12:48 UTC, delrueba requested changes

2018-11-23 12:48 UTC, delrueba commented on templates/custom/vesta/vesta--teaser-with-link.html.twig
> +      <a href="{{ url }}" class="standalone-link">{{ entity.name }}</a>
No links in titles.

2018-11-26 08:34 UTC, MPParsley commented on gent_base.theme
> +      $variables["items"][$key]['attributes']->addClass('teaser', 'teaser-contact');
```suggestion
      $variables['items'][$key]['attributes']->addClass('teaser', 'teaser-contact');
```

2018-11-26 08:34 UTC, MPParsley commented on gent_base.theme
> +      $variables["items"][$key]['attributes']->addClass('teaser', 'teaser-contact');
```suggestion
      $variables['items'][$key]['attributes']->addClass('teaser', 'teaser-contact');
```

2018-11-26 08:35 UTC, MPParsley commented on gent_base.theme
> +    $variables["items"][$key]["content"]["#options"]['attributes']['class'][] = 'standalone-link';
```suggestion
    $variables['items'][$key]['content']['#options']['attributes']['class'][] = 'standalone-link';
```

2018-11-26 08:35 UTC, MPParsley approved these changes

2018-11-26 08:48 UTC, meirege commented on templates/custom/vesta/vesta--teaser-with-link.html.twig
> +      <a href="{{ url }}" class="standalone-link">{{ entity.name }}</a>
👍

2018-11-28 07:58 UTC, delrueba approved these changes

2018-11-28 09:02 UTC, merged