DTGB-672: Refactored molecules and organisms component structure.
digipolisgent/drupal_theme_gent-base pull request #568
Opened 2019-01-16 12:40 UTC by meirege

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.
- [ ] I have ran gulp axe on the compiled files and found no errors.

2019-01-16 12:59 UTC, delrueba commented
Why is there now a h2 in a description term?

2019-01-21 11:34 UTC, meirege commented
@delrueba Seems fine to me... The H2 has been used in other components before though... I just copied it from another collated component...

2019-01-21 11:54 UTC, delrueba requested changes
I would advise against using h2 tags inside a dt.
It's not correctin the document structure (there's no h1) and it's information overload.

Looks like headings are being used as styling elements.

2019-01-21 11:54 UTC, delrueba commented on styleguide/components/31-molecules/figure/figure.config.js
> +  preview: '@preview-description-list',
You need to add 'preview: '@preview'' to the variants.

2019-01-21 11:54 UTC, delrueba commented on styleguide/components/41-organisms/collection/collection.config.js
> +  preview: '@preview-description-list',
Update variants preview.

2019-01-21 11:54 UTC, delrueba commented
> @delrueba Seems fine to me... The H2 has been used in other components before though... I just copied it from another collated component...

I like that you're going for uniformity!
But I fear you've done it the wrong way round ;)

2019-01-21 13:02 UTC, meirege commented
@delrueba Implemented your changes.

2019-01-22 12:33 UTC, hstandaert approved these changes

2019-01-30 14:00 UTC, delrueba approved these changes

2019-01-30 15:06 UTC, merged