DTGB-665: Added layouts.
digipolisgent/drupal_theme_gent-base pull request #569
Opened 2019-01-16 15:17 UTC by meirege

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.
- [ ] I have ran gulp axe on the compiled files and found no errors.

2019-01-17 08:01 UTC, hstandaert reviewed
Seems like there's a problem with the image gallery 🤔

![screenshot 2019-01-17 at 08 03 06](https://user-images.githubusercontent.com/4415097/51303692-6a91b180-1a36-11e9-9e91-2defdc4c2f1b.png)

2019-01-18 08:06 UTC, delrueba commented
> Seems like there's a problem with the image gallery thinking
> 
> ![screenshot 2019-01-17 at 08 03 06](https://user-images.githubusercontent.com/4415097/51303692-6a91b180-1a36-11e9-9e91-2defdc4c2f1b.png)

I like it.

2019-01-21 11:44 UTC, hstandaert requested changes

2019-01-21 11:44 UTC, hstandaert commented on CHANGELOG.md
> +* DTGB-665: Refactored pages to only show layouts. This shouldn't affect any
Not sure if this belongs in the `gent-base` CHANGELOG, since only styleguide was affected by these changes.

2019-01-21 11:56 UTC, delrueba requested changes

2019-01-21 11:56 UTC, delrueba commented on styleguide/components/41-organisms/header/header.config.js
> +      name: 'logged-in',
preview: '@preview'

2019-01-21 12:00 UTC, hstandaert commented on styleguide/components/41-organisms/header/header.config.js
> +      name: 'logged-in',
```suggestion
      name: 'logged-in',
      preview: '@preview'
```

2019-01-21 12:29 UTC, meirege commented on CHANGELOG.md
> +* DTGB-665: Refactored pages to only show layouts. This shouldn't affect any
I removed it. You where right :)

2019-01-21 12:29 UTC, meirege commented on styleguide/components/41-organisms/header/header.config.js
> +      name: 'logged-in',
Added it.

2019-01-21 12:35 UTC, hstandaert approved these changes

2019-01-21 13:04 UTC, delrueba approved these changes

2019-01-21 13:05 UTC, merged