DTGB-491: Added theming for dg_maps
digipolisgent/drupal_theme_gent-base pull request #581
Opened 2019-01-22 13:14 UTC by hstandaert

## Description

Added theming for the output for the `dg_maps` module.

### Remarks
**Javascript**
Some of the JS behaviors for dg_maps had to be overridden and resulted in some code that was duplicated and slightly adapted (since we don't have any other option to do this)

**Theming**
Since we don't control the markup for the maps, we have to scope the css to the provided selectors

### Trivial
- Added `js:watch` task to gent-base gulpfile

## Motivation and Context

## How Has This Been Tested?

- Local environment
- In multiple browsers

## Screenshots (if appropriate):
![screenshot 2019-01-22 at 14 11 12](https://user-images.githubusercontent.com/4415097/51537720-97d3ca80-1e4f-11e9-8213-48e356c1738f.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [x] I have updated the gent_base CHANGELOG accordingly.
- [x] I have ran gulp axe on the compiled files and found no errors.

2019-01-24 09:17 UTC, delrueba requested changes

2019-01-24 09:17 UTC, delrueba commented on gent_base.libraries.yml
> +    - gent_base/accordion
Why is this double?

2019-01-24 09:17 UTC, delrueba commented on source/gulpfile.js
> + *;
```suggestion
 *
```

2019-01-24 09:17 UTC, delrueba commented on source/gulpfile.js
> +gulp.task('watch', gulp.series('default'))
```suggestion
gulp.task('watch', gulp.series('default'));
```

2019-01-24 09:17 UTC, delrueba commented on source/js/dg_maps.functions.js
> +    this.categories_ = typeof options.categories !== 'undefined' ? options.categories : [];
```suggestion
    this.categories_ = options.categories || [];
```

2019-01-24 09:17 UTC, delrueba commented on source/js/dg_maps.functions.js
> +    this.categories_ = typeof options.categories !== 'undefined' ? options.categories : [];
undefined is falsy

2019-01-24 09:17 UTC, delrueba commented on source/js/dg_maps.functions.js
> +    this.layerGroupIcon_ = typeof options.layerGroupIcon !== 'undefined' ? options.layerGroupIcon : void 0;
see above

2019-01-24 09:17 UTC, delrueba commented on source/js/dg_maps.functions.js
> +    this.legend_ = typeof options.legend !== 'undefined' ? options.legend : {};
see above

2019-01-24 09:17 UTC, delrueba commented on source/js/dg_maps.functions.js
> +    if (legendData.length > 0) {
```suggestion
    if (legendData.length) {
```

2019-01-24 09:17 UTC, delrueba commented on source/js/dg_maps.functions.js
> +      legendIcon.alt = layerIcon.label ? layerIcon.label : '';
simplify

2019-01-24 09:17 UTC, delrueba commented on source/js/dg_maps.functions.js
> +    if (legendData.length > 0) {
Just noticed you also check (legendData.length > 1) further down.
You can ignore this suggestion in favour of code clarity.

2019-01-24 09:17 UTC, delrueba commented on source/js/dg_maps.functions.js
> +          legendItemIcon.className = 'legend__item__label';
Move to above codeblock.

2019-01-24 09:17 UTC, delrueba commented on source/sass/31-molecules/map/_map.scss
> +        padding: 0 1ch;
:trophy:

2019-01-24 09:17 UTC, delrueba commented on templates/contrib/dg_maps/dg-maps-map-region.html.twig
> +  <button type="button" class="map-region-button {{ hide_on_mobile }}" data-toggle-region="{{ name }}" title="{{ "Toggle @name region"|t({ '@name': name }) }}">
Is this a toggle button?
Would suggest using aria-expanded or aria-pressed.
Only if you're certain that you can manage the states.

2019-01-24 09:40 UTC, hstandaert commented
@delrueba, I'm going to resolve all your comments regarding the javascript improvements, since this is code that is copy-pasted from the `dg_maps` module. 

Even though your comments are justified, I don't think it makes much sense to optimize third-party code. It'll only make maintenance harder when`dg_maps` is updated.

(Correct me if I'm wrong about this 😆)

2019-01-24 10:12 UTC, delrueba commented
> @delrueba, I'm going to resolve all your comments regarding the javascript improvements, since this is code that is copy-pasted from the `dg_maps` module.
> 
> Even though your comments are justified, I don't think it makes much sense to optimize third-party code. It'll only make maintenance harder when`dg_maps` is updated.
> 
> (Correct me if I'm wrong about this laughing)

Well, you can always contribute to dg_maps :stuck_out_tongue:

2019-01-24 15:55 UTC, delrueba approved these changes

2019-01-25 11:58 UTC, meirege approved these changes

2019-01-25 12:21 UTC, merged