DTGB-659: Reverted tablet breakpoint to 768px
digipolisgent/drupal_theme_gent-base pull request #590
Opened 2019-01-28 13:27 UTC by hstandaert

## Description

- Changed tablet breakpoint back to `768px`
- Optimized styling for some components: 
  - Footer
  - Filter layout

## Motivation and Context

Tablet breakpoint was `769px`, which doesn't make sense because iPad portrait (for example) is not included in this range.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the style guide CHANGELOG accordingly.
- [x] I have ran gulp axe on the compiled files and found no errors.

2019-01-29 08:48 UTC, meirege requested changes

2019-01-29 08:48 UTC, meirege commented on styleguide/components/61-layouts/sidebar-layout/_sidebar-layout.scss
> +    //@include tablet {
Remove commented code.

2019-01-29 08:48 UTC, meirege commented on styleguide/components/61-layouts/sidebar-layout/_sidebar-layout.scss
> +    //@include tablet {
Remove commented code.

2019-01-29 08:48 UTC, meirege commented on styleguide/components/41-organisms/footer/_footer.scss
> +    //@include tablet {
Remove commented code.

2019-01-29 08:48 UTC, meirege commented on styleguide/components/41-organisms/footer/_footer.scss
> +        //@include tablet {
Remove commented code.

2019-01-30 08:43 UTC, delrueba approved these changes

2019-01-30 10:05 UTC, meirege approved these changes

2019-01-30 10:05 UTC, merged