8.x-3.0-beta1
digipolisgent/drupal_theme_gent-base pull request #627
Opened 2019-03-11 14:45 UTC by hstandaert

# CHANGELOG
## Added

* DTGB-491: Added [`dg_maps`](https://github.com/digipolisgent/drupal_module_dg-maps) theming
* Tabs/local tasks theming
    > :warning: The tabs block should ideally be placed in the admin region. 

## Removed

* DTGB-683: Frequently visited.
* DTGB-700: [Styleguide](https://github.com/StadGent/fractal_styleguide_gent-base) as a part of gent-base. It is integrated as an npm dependency now.

# How to upgrade

Since we use source files from the styleguide to build our own assets, we'll have to update some paths in our custom themes as well. More specifically, the themes that are based on the starterkit. 

To make this easier, you can download+execute a remote script that replaces the paths for you. It only needs to know the path to your custom theme.

1. `cd` into the root directory of your Drupal project
2. Set the `THEME_FOLDER` variable to the path where your custom theme is located. Make it relative to you current directory.

    ```bash
    export THEME_FOLDER=./web/themes/custom/{your_theme}
    ```

3. Execute the remote script to find & replace the references to the removed `styleguide` folder

    ```bash
    wget https://git.io/fhxXh -O - | sh
    ```

2019-03-12 07:31 UTC, zero2one commented
There is a lot of javascript code to alter/add the dg_maps functionality. This should be added to the dg_maps module instead so all projects can use this functionality.

2019-03-12 07:33 UTC, hstandaert commented
> There is a lot of javascript code to alter/add the dg_maps functionality. This should be added to the dg_maps module instead so all projects can use this functionality.

@zero2one, these are strictly styling overrides (since a lot of the markup is built in javascript in the dg_maps module), so I don't think it's useful for non-styleguide projects.

2019-03-12 07:35 UTC, zero2one requested changes

2019-03-12 07:35 UTC, zero2one commented on gent_base.theme
>   * Implements hook_preprocess_HOOK().
Implements hook_preprocess_paragraph__contact().

2019-03-12 07:35 UTC, zero2one commented on gent_base.theme
> + * Implements hook_preprocess_HOOK().
Implements hook_preprocess_dg_maps_map().

2019-03-12 07:35 UTC, zero2one commented on templates/contrib/dg_maps/dg-maps-map-region.html.twig
> +'map-region--' ~ name,
If no name is present a class name `map-region--` will be added.

2019-03-12 07:35 UTC, zero2one commented on templates/contrib/dg_maps/dg-maps-map.html.twig
> +
Single empty line.

2019-03-12 07:35 UTC, zero2one commented on templates/custom/vesta/vesta.html.twig
> -
Why is the (required) empty line on the end of the file removed?

2019-03-12 07:35 UTC, zero2one commented on templates/contrib/facets/facets-summary-item-list.html.twig
> -
Why is the (required) empty line on the end of the file removed?

2019-03-12 07:35 UTC, zero2one commented on source/js/dg_maps.baselayerswitcher.js
> +
Remove empty line (there can be only one).

2019-03-12 07:35 UTC, zero2one commented on source/js/dg_maps.baselayerswitcher.js
> +
Remove empty line.

2019-03-12 07:35 UTC, zero2one commented on source/js/dg_maps.bindings.js
> +      for (var s = selected.length; s--;) {
A lot of nesting going on here...
Better to put sub-nesting in separate functions.

2019-03-12 07:35 UTC, zero2one commented on CHANGELOG.md
> +* DTGB-491: Added [`dg_maps`](https://github.com/digipolisgent/drupal_module_dg-maps) theming
Sentenced should end with a full stop (.).

2019-03-12 07:35 UTC, zero2one commented on CHANGELOG.md
> +* DTGB-700: [Styleguide](https://github.com/StadGent/fractal_styleguide_gent-base) as a part of gent-base. It is integrated as an npm dependency now.
Lines should not be longer than 80 characters.

2019-03-20 07:49 UTC, zero2one approved these changes

2019-03-20 10:08 UTC, merged