DTGB-417: Fixed some things for use in D8.
digipolisgent/drupal_theme_gent-base pull request #79
Opened 2018-04-03 11:06 UTC by meirege

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.

2018-04-03 12:23 UTC, Jeroen005 requested changes

2018-04-03 12:23 UTC, Jeroen005 commented on source/sass/11-base/contextual-links/_contextual-links.scss
> +    background-repeat:no-repeat;
space

2018-04-03 12:23 UTC, Jeroen005 commented on styleguide/components/11-base/fonts/_icons_template.template
> +[class^='<%= cssClass%>'],
bewust? je moet hem nu vooraan  in het attr gebruiken :)

2018-04-03 12:23 UTC, Jeroen005 commented on templates/core/misc/status-messages.html.twig
> +        <p>
Is deze p noodzakelijk?

2018-04-04 07:09 UTC, meirege commented on source/sass/11-base/contextual-links/_contextual-links.scss
> +    background-repeat:no-repeat;
Fixed.

2018-04-04 07:09 UTC, meirege commented on styleguide/components/11-base/fonts/_icons_template.template
> +[class^='<%= cssClass%>'],
Fixed.

2018-04-04 07:10 UTC, meirege commented on templates/core/misc/status-messages.html.twig
> +        <p>
Nope, I deleted it.

2018-04-04 07:19 UTC, merged