DTGB-792: Changed footer element to section element to make sure html…
digipolisgent/drupal_theme_gent-base pull request #802
Opened 2019-12-23 08:29 UTC by pj-claeys

… is valid.

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.

2019-12-23 09:18 UTC, delrueba reviewed
Is een footer omdat die in stijlgids in een article zit.
https://stijlgids.stad.gent/v3/components/detail/mijn-gent-block--logged-in.html

Kan zijn dat je aanpassing styling gaat breken.

2019-12-23 10:41 UTC, delrueba requested changes
Better make the containing element an article.
I fear it's less clear to what these sections belong if you don't wrap them in a semantic element.

2019-12-23 10:59 UTC, delrueba approved these changes

2020-01-02 08:04 UTC, MPParsley approved these changes

2020-01-02 13:00 UTC, closed without merging