Feature/DTGB-406: First implementation of the standard footer.
digipolisgent/drupal_theme_gent-base pull request #81
Opened 2018-04-04 06:55 UTC by meirege

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the style guide CHANGELOG accordingly.
- [ ] I have updated the gent_base CHANGELOG accordingly.

2018-04-05 15:33 UTC, delrueba commented on styleguide/components/11-base/fonts/_fonts.scss
> +@import url('https://fonts.googleapis.com/css?family=Fira+Sans:400,600,700,800'); // sass-lint:disable-line no-url-protocols
I know this is not your decision, but has design been made aware that we are adding an extra font weight?
At this rate, we'll end up with all font variants before the end of this month. Despite a clear resolution not to.

2018-04-10 14:20 UTC, delrueba approved these changes

2018-04-10 14:48 UTC, Jeroen005 requested changes

2018-04-10 14:48 UTC, Jeroen005 commented on styleguide/components/31-molecules/blocks/disclaimer-block/disclaimer-block.twig
> +    'h3_text': 'Nuttige links'
Always use English copy in stijlgids.

2018-04-10 14:48 UTC, Jeroen005 commented on styleguide/components/31-molecules/blocks/post-address-block/post-address-block.twig
> +    'h3_text': 'Postadres'
English

2018-04-10 14:48 UTC, Jeroen005 commented on styleguide/components/31-molecules/islands/gentinfo-island/gentinfo-island.twig
> +        'text': 'Gentinfo is bereikbaar van maandag t.e.m. zaterdag van 08:00 tot 19:00'
English

2018-04-11 06:54 UTC, meirege commented on styleguide/components/31-molecules/blocks/disclaimer-block/disclaimer-block.twig
> +    'h3_text': 'Nuttige links'
Changed it to English.

2018-04-11 06:54 UTC, meirege commented on styleguide/components/31-molecules/blocks/post-address-block/post-address-block.twig
> +    'h3_text': 'Postadres'
Changed it to English.

2018-04-11 06:54 UTC, meirege commented on styleguide/components/31-molecules/islands/gentinfo-island/gentinfo-island.twig
> +        'text': 'Gentinfo is bereikbaar van maandag t.e.m. zaterdag van 08:00 tot 19:00'
Changed it to English.

2018-04-12 07:12 UTC, Jeroen005 approved these changes

2018-04-12 07:15 UTC, merged